name: yohhanp
favicon: null
layout_spectrum: 0.75055
typography_spectrum: 0.1846437759231776
title: Yohhan P
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.8015062951017171
  rhythmicContrast: 0.5
purpose: []
