name: yohhanp
favicon: null
layout_spectrum: 0.89468
typography_spectrum: 0.12195
title: Yohhan P
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7eb9c7'
    - '#d77955'
    - '#4d4b4c'
    - '#d9ddde'
    - '#1f232c'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.8015062951017171
  rhythmicContrast: 0.25
purpose: []
